"use client";

import { Toast } from "@/components";
import Navbar from "@/layouts/users/Navbar";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function UserLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            <Toast />

            {children}
        </>
    );
}
