import { NextIntlClientProvider } from "next-intl";
import "./globals.css";
import StoreProvider from "@/lib/storeProvider";
import { getLocale, getMessages } from "next-intl/server";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const messages = await getMessages();
    const locale = await getLocale();

    return (
        <html
            lang={locale}
            dir={locale == "ar" ? "rtl" : "ltr"}
        >
            <NextIntlClientProvider messages={messages}>
                <StoreProvider>
                    <body>{children}</body>
                </StoreProvider>
            </NextIntlClientProvider>
        </html>
    );
}
