"use client";

import { Toast } from "@/components";
import "./globals.css";
import StoreProvider from "@/lib/storeProvider";
import Navbar from "@/layouts/Navbar";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <StoreProvider>
                <body>
                    <Navbar />
                    <Toast />
                    {children}
                </body>
            </StoreProvider>
        </html>
    );
}
