"use client";

import { Toast } from "@/components";
import TokenState from "@/interfaces/states/TokenState";
import Navbar from "@/layouts/admins/Navbar";
import { useAppDispatch, useAppSelector } from "@/lib/hooks";
import { adminTokenSet } from "@/redux/SetToken";
import { useEffect } from "react";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const dispatch = useAppDispatch();

    const tokenState = useAppSelector(
        (state: { setToken: TokenState }) => state.setToken
    );

    useEffect(() => {
        const token = localStorage.getItem("adminToken");
        if (token) {
            dispatch(adminTokenSet());
        }
    });

    return (
        <>
            {tokenState.isAdminToken ? <Navbar /> : null}

            <Toast />

            {children}
        </>
    );
}
